image: gitpod/workspace-full

tasks:
  - name: Setup
    init: |
      composer install
      cp .env.example .env || true

  - name: Run Server
    command: |
      php -S 0.0.0.0:8080 -t public

ports:
  - port: 8080
    onOpen: open-preview