FROM php:8.2-cli-alpine

RUN apk add --no-cache git zip unzip linux-headers \
    && docker-php-ext-install pdo pdo_mysql pdo_sqlite

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

CMD ["sh", "-c", "composer install && php -S 0.0.0.0:8080 -t public"]
