<?php

declare(strict_types=1);

use App\Controllers\UserController;
use App\Controllers\AuthController;
use App\Middleware\CorsMiddleware;
use App\Middleware\JsonMiddleware;
use Siro\Core\Lang;

$app->router->get('/', function (): array {
    return [
        'success' => true,
        'message' => Lang::get('messages.welcome'),
        'data' => [
            'name' => 'Siro API Framework',
            'version' => '0.13.0',
            'php' => PHP_VERSION,
            'locale' => Lang::locale(),
        ],
        'meta' => [],
    ];
});

$app->router->group('/api', [CorsMiddleware::class], function ($router): void {
    // Public auth routes
    $router->post('/auth/register', [AuthController::class, 'register'])
        ->middleware([JsonMiddleware::class, 'throttle:30,1']);

    $router->post('/auth/login', [AuthController::class, 'login'])
        ->middleware([JsonMiddleware::class, 'throttle:60,1']);

    $router->post('/auth/refresh', [AuthController::class, 'refresh'])
        ->middleware([JsonMiddleware::class, 'throttle:30,1']);

    $router->post('/auth/forgot-password', [AuthController::class, 'forgotPassword'])
        ->middleware([JsonMiddleware::class, 'throttle:10,1']);

    $router->post('/auth/reset-password', [AuthController::class, 'resetPassword'])
        ->middleware([JsonMiddleware::class, 'throttle:10,1']);

    $router->post('/auth/verify-email', [AuthController::class, 'verifyEmail'])
        ->middleware([JsonMiddleware::class, 'throttle:10,1']);

    // Protected auth routes
    $router->get('/auth/me', [AuthController::class, 'me'])
        ->middleware(['auth', 'throttle:120,1']);

    $router->post('/auth/logout', [AuthController::class, 'logout'])
        ->middleware(['auth', 'throttle:60,1']);

    // CRUD routes
    $router->get('/users', [UserController::class, 'index'])->cache(60);
    $router->get('/users/{id}', [UserController::class, 'show'])->cache(60);

    $router->post('/users', [UserController::class, 'store'])
        ->middleware([JsonMiddleware::class, 'auth', 'throttle:60,1']);

    $router->put('/users/{id}', [UserController::class, 'update'])
        ->middleware([JsonMiddleware::class, 'auth', 'throttle:60,1']);

    $router->delete('/users/{id}', [UserController::class, 'delete'])
        ->middleware(['auth', 'throttle:60,1']);

    // Product routes
    $router->get('/products', [\App\Controllers\ProductController::class, 'index']);
    $router->get('/products/{id}', [\App\Controllers\ProductController::class, 'show']);
    $router->post('/products', [\App\Controllers\ProductController::class, 'store'])
        ->middleware([JsonMiddleware::class]);
    $router->put('/products/{id}', [\App\Controllers\ProductController::class, 'update'])
        ->middleware([JsonMiddleware::class]);
    $router->delete('/products/{id}', [\App\Controllers\ProductController::class, 'delete']);
    // Generated by: php siro make:crud testcmdcrud
    $router->get('/testcmdcrud', [\App\Controllers\TestcmdcrudController::class, 'index']);
    $router->get('/testcmdcrud/{id}', [\App\Controllers\TestcmdcrudController::class, 'show']);
    $router->post('/testcmdcrud', [\App\Controllers\TestcmdcrudController::class, 'store'])
        ->middleware([JsonMiddleware::class]);
    $router->put('/testcmdcrud/{id}', [\App\Controllers\TestcmdcrudController::class, 'update'])
        ->middleware([JsonMiddleware::class]);
    $router->delete('/testcmdcrud/{id}', [\App\Controllers\TestcmdcrudController::class, 'delete']);
});