<?php

declare(strict_types=1);

use App\Controllers\UserController;
use App\Controllers\AuthController;
use App\Middleware\CorsMiddleware;
use App\Middleware\JsonMiddleware;
use Siro\Core\Lang;

$app->router->get('/', function (): array {
    return [
        'success' => true,
        'message' => Lang::get('messages.welcome'),
        'data' => [
            'name' => 'Siro API Framework',
            'version' => '0.15.1',
            'php' => PHP_VERSION,
            'locale' => Lang::locale(),
        ],
        'meta' => [],
    ];
});

$app->router->get('/health', function (): array {
    $dbOk = false;
    try {
        \Siro\Core\Database::connection()->query('SELECT 1');
        $dbOk = true;
    } catch (\Throwable) {
    }
    return [
        'success' => true,
        'message' => 'OK',
        'data' => [
            'status' => 'healthy',
            'version' => '0.15.1',
            'php' => PHP_VERSION,
            'database' => $dbOk ? 'connected' : 'unreachable',
            'time' => date('c'),
        ],
    ];
});

$app->router->group('/api', [CorsMiddleware::class], function ($router): void {
    // Public auth routes
    $router->post('/auth/register', [AuthController::class, 'register'])
        ->middleware([JsonMiddleware::class, 'throttle:30,1']);

    $router->post('/auth/login', [AuthController::class, 'login'])
        ->middleware([JsonMiddleware::class, 'throttle:60,1']);

    $router->post('/auth/refresh', [AuthController::class, 'refresh'])
        ->middleware([JsonMiddleware::class, 'throttle:30,1']);

    $router->post('/auth/forgot-password', [AuthController::class, 'forgotPassword'])
        ->middleware([JsonMiddleware::class, 'throttle:10,1']);

    $router->post('/auth/reset-password', [AuthController::class, 'resetPassword'])
        ->middleware([JsonMiddleware::class, 'throttle:10,1']);

    $router->post('/auth/verify-email', [AuthController::class, 'verifyEmail'])
        ->middleware([JsonMiddleware::class, 'throttle:10,1']);

    // Protected auth routes
    $router->get('/auth/me', [AuthController::class, 'me'])
        ->middleware(['auth', 'throttle:120,1']);

    $router->post('/auth/logout', [AuthController::class, 'logout'])
        ->middleware(['auth', 'throttle:60,1']);

    // CRUD routes
    $router->get('/users', [UserController::class, 'index'])->cache(60);
    $router->get('/users/{id}', [UserController::class, 'show'])->cache(60);

    $router->post('/users', [UserController::class, 'store'])
        ->middleware([JsonMiddleware::class, 'auth', 'throttle:60,1']);

    $router->put('/users/{id}', [UserController::class, 'update'])
        ->middleware([JsonMiddleware::class, 'auth', 'throttle:60,1']);

    $router->delete('/users/{id}', [UserController::class, 'delete'])
        ->middleware(['auth', 'throttle:60,1']);

    // Product routes
    $router->get('/products', [\App\Controllers\ProductController::class, 'index']);
    $router->get('/products/{id}', [\App\Controllers\ProductController::class, 'show']);
    $router->post('/products', [\App\Controllers\ProductController::class, 'store'])
        ->middleware([JsonMiddleware::class]);
    $router->put('/products/{id}', [\App\Controllers\ProductController::class, 'update'])
        ->middleware([JsonMiddleware::class]);
    $router->delete('/products/{id}', [\App\Controllers\ProductController::class, 'delete']);
    // Generated by: php siro make:crud categories
    $router->get('/categories', [\App\Controllers\CategoryController::class, 'index']);
    $router->get('/categories/{id}', [\App\Controllers\CategoryController::class, 'show']);
    $router->post('/categories', [\App\Controllers\CategoryController::class, 'store'])
        ->middleware([JsonMiddleware::class]);
    $router->put('/categories/{id}', [\App\Controllers\CategoryController::class, 'update'])
        ->middleware([JsonMiddleware::class]);
    $router->delete('/categories/{id}', [\App\Controllers\CategoryController::class, 'delete']);
    // Generated by: php siro make:crud tag
    $router->get('/tag', [\App\Controllers\TagController::class, 'index']);
    $router->get('/tag/{id}', [\App\Controllers\TagController::class, 'show']);
    $router->post('/tag', [\App\Controllers\TagController::class, 'store'])
        ->middleware([JsonMiddleware::class]);
    $router->put('/tag/{id}', [\App\Controllers\TagController::class, 'update'])
        ->middleware([JsonMiddleware::class]);
    $router->delete('/tag/{id}', [\App\Controllers\TagController::class, 'delete']);
    // Generated by: php siro make:crud orders
    $router->get('/orders', [\App\Controllers\OrderController::class, 'index']);
    $router->get('/orders/{id}', [\App\Controllers\OrderController::class, 'show']);
    $router->post('/orders', [\App\Controllers\OrderController::class, 'store'])
        ->middleware([JsonMiddleware::class]);
    $router->put('/orders/{id}', [\App\Controllers\OrderController::class, 'update'])
        ->middleware([JsonMiddleware::class]);
    $router->delete('/orders/{id}', [\App\Controllers\OrderController::class, 'delete']);
    // Generated by: php siro make:crud posts
    $router->get('/posts', [\App\Controllers\PostController::class, 'index']);
    $router->get('/posts/{id}', [\App\Controllers\PostController::class, 'show']);
    $router->post('/posts', [\App\Controllers\PostController::class, 'store'])
        ->middleware([JsonMiddleware::class]);
    $router->put('/posts/{id}', [\App\Controllers\PostController::class, 'update'])
        ->middleware([JsonMiddleware::class]);
    $router->delete('/posts/{id}', [\App\Controllers\PostController::class, 'delete']);

    // Upload & Lang demo routes
    $router->post('/upload/avatar', function (\Siro\Core\Request $req): \Siro\Core\Response {
        $file = $req->file('avatar');
        if ($file === null || !$file->isValid()) {
            return \Siro\Core\Response::error('No file uploaded', 422);
        }
        $path = $file->store('avatars');
        return \Siro\Core\Response::success([
            'path' => $path,
            'url' => \Siro\Core\Storage::url($path),
            'original_name' => $file->originalName(),
            'size' => $file->size(),
            'mime' => $file->mime(),
        ], 'Avatar uploaded');
    })->middleware([JsonMiddleware::class]);

    $router->get('/profile', function (\Siro\Core\Request $req): array {
        $locale = $req->query('locale', 'en');
        \Siro\Core\Lang::setLocale($locale);

        $name = $req->query('name', 'Guest');
        $greeting = \Siro\Core\Lang::get('messages.greeting', ['name' => $name]);

        return [
            'success' => true,
            'message' => $greeting,
            'data' => [
                'name' => $name,
                'locale' => $locale,
                'greeting' => $greeting,
                'messages_count' => \Siro\Core\Lang::count('validation'),
                'available_locales' => ['en', 'vi'],
            ],
        ];
    });
});
