apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "siro-api.fullname" . }}-env
  labels:
    {{- include "siro-api.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.env.APP_DEBUG | quote }}
  APP_NAME: {{ .Values.env.APP_NAME | quote }}
  DB_CONNECTION: {{ .Values.env.DB_CONNECTION | quote }}
  DB_DATABASE: {{ .Values.env.DB_DATABASE | quote }}
  CACHE_DRIVER: {{ .Values.env.CACHE_DRIVER | quote }}
  SESSION_DRIVER: {{ .Values.env.SESSION_DRIVER | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  JWT_ALGORITHM: {{ .Values.jwt.algorithm | quote }}
  JWT_TTL: {{ .Values.jwt.ttl | quote }}
  JWT_REFRESH_TTL: {{ .Values.jwt.refreshTtl | quote }}
