apiVersion: v1
kind: Secret
metadata:
  name: {{ include "siro-api.fullname" . }}-jwt
  labels:
    {{- include "siro-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ include "siro-api.jwtSecret" . }}
